version: '3.3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
